### ISSUE TITLE
Ng serve

### ISSUE THREAD

**Issue by herel** [joseguerra/master#1]
ng serve
/usr/local/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-class-factory.js:34
            result.push(...indices);
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/index.js:3:30)

**Comment by joseguerra** [comment]
Dale npm install y luego ng server
Eso debería funcionar

Obtener Outlook para Android<https://aka.ms/ghei36>


________________________________
